---
- name: Installing Nagios Web Interface for Ubuntu
  shell:  |
    cd ~
    cd /tmp/nagios-4.4.6
    make install-webconf
    expect: htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin
    a2enmod rewrite cgi
    systemctl restart apache2
